version: '3'

services:
  web:
    #웹 어플리케이션 설정
    depends_on: 
      - database
  #이미지 파일 이름  image: ~~~~
    ports:
      - "8000:5000"

    network:
      - my-bob-network

  database:
    image: mysql:5.7
    ports:
      - "3333:3306"

    #volumes:
     # - ./database:/var/lib/docker

    enviroment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true

    network:
      - my-bob-network 

network:
  my-bob-network:

#volumes:
  # my-bob-database: